### ISSUE TITLE
What is this 40 in the im shape?

### ISSUE THREAD

**Issue by rik030** [mdciri/Vox2Vox#10]
Hello sir, what is this 40 in the imshape?

![image](https://user-images.githubusercontent.com/45557871/156544533-f8ada42f-9a1c-4371-b985-6c478ee610a9.png)

**Comment by mdciri** [comment]
Dear Rishav

That 40 is the number of channels of the input.

In my paper I explained that I trained 10 model doing a 10-fold cross
validation where each of them has an out with 4 channel. I took these 10
outputs (the scores before the softmax function) and concatenated them to
each other, hence 40 channels.


/Marco
