### ISSUE TITLE
Test Prediction

### ISSUE THREAD

**Issue by fitriaurbach0014** [mdciri/Vox2Vox#11]
How to make test prediction from the trained model? Thank you

**Comment by mdciri** [comment]
Dear fitriaurbach0014,

The Vox2Vox repository does not provide the pre-trained model if it is that
what do you mean.
You should train the model and get your predictions from the generator's
outputs.

In other words, define your generator (G) and discriminator (D), train
them, and then get your predictions doing:
gen_output = G(image, training=False)


Best regards,
Marco


Il giorno sab 26 mar 2022 alle ore 23:40 fitriaurbach0014 <
***@***.***> ha scritto:

**Comment by fitriaurbach0014** [comment]
Okay, thank you Sir. Because I have trained the model and still confused how to get the prediction. I will try your suggestion
