### ISSUE TITLE
Is it possible to implement Vox2Vox for 2D medical images?

### ISSUE THREAD

**Issue by fitriaurbach0014** [mdciri/Vox2Vox#12]
Hello Sir,
I want to ask, is it possible to implement Vox2Vox for 2D medical images? Because I have the final year project to segment meningioma using Vox2Vox. But the data I get from the hospital is 2D.

If it is possible to implement Vox2Vox for 2D medical images, which part do I have to modify sir?
Sorry If I ask too much, because I'm a beginner in this field.
Thank you, Sir.

**Comment by mdciri** [comment]
Dear fitriaurbach001,

You can simply edit each 3D layer into a 2D layer. Anyway, to implement the
Vox2Vox, I was inspired by the Pix2Pix <https://arxiv.org/abs/1611.07004>
by Isola (GitHub repository <https://github.com/phillipi/pix2pix>, TensorFlow
tutorial <https://www.tensorflow.org/tutorials/generative/pix2pix>) which
is for 2D images. Moreover, you can read a review paper about GANs used in
medicine, Pix2Pix included, here
<https://www.researchgate.net/profile/Khalid-Raza-2/publication/341565298_Medical_Image_Generation_using_Generative_Adversarial_Networks/links/602976faa6fdcc37a82903cb/Medical-Image-Generation-using-Generative-Adversarial-Networks.pdf>
.

If you have a look at these links, you should not have any problem doing
your project.


Best regards,
Marco

Il giorno mer 6 apr 2022 alle ore 10:29 fitriaurbach0014 <
***@***.***> ha scritto:
