### ISSUE TITLE
Hausdorff distance

### ISSUE THREAD

**Issue by fitriaurbach0014** [mdciri/Vox2Vox#14]
Hello Sir
As I see in your paper, there is Hausdorff Distance as one of the training metrics. But, when I ran the code, I couldn't find the Hausdorff distance. Could I know the code to calculate Hausdorff Distance Sir? Because I still get errors in my own code. 
Thank you in advance Sir

**Comment by mdciri** [comment]
https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_hausdorff_distance.html
