### ISSUE TITLE
error from utils.py

### ISSUE THREAD

**Issue by a0923777314** [mdciri/Vox2Vox#6]
in utils.py line 111:
X_aug, y_aug = combine_aug(X_aug, y_aug)
shown error as below.
combine_aug() missing 1 required positional argument: 'do'

please help to fix the error, thanks.

**Comment by mdciri** [comment]
Thanks for the report. I fixed the issue.

**Comment by a0923777314** [comment]
it's working.
but it shows errors:
2021-05-26 04:20:54.849259: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 1.15G (1237407744 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

What parameters can I modify?

**Comment by a0923777314** [comment]
I deleted training data until remain 3 folders.
Then running code and shows an error in train_v2v.py line 97 as below :
local variable 'Xb' referenced before assignment

**Comment by a0923777314** [comment]
Hi, mdciri

in train_v2v.py line 97 as below :
local variable 'Xb' referenced before assignment

please help to fix the error as above qwuestion.
thank you.

**Comment by siyi-xun** [comment]
Hello, I have the same problem.

in train_v2v.py line 97 as below :
local variable 'Xb' referenced before assignment

please help to fix the error as above qwuestion.
thank you.
