### ISSUE TITLE
error in train v2v file

### ISSUE THREAD

**Issue by divyadaiict** [mdciri/Vox2Vox#7]
history['train'] and history['valid'] both has different indentation in trainv2v file could please me know whether it is supposed to be this way or there is some error because I am facing indentation error in that lines

**Comment by mdciri** [comment]
Dear Divyadaiict,

I do not see such error. Can you, please, tell me in which lines?
Anyway they are both initialized at the beginning of the training and
updated after every training and validation epoch respectively (hence after
the respective for loop).


Best regards,
Marco Domenico Cirillo




Il giorno mar 22 giu 2021 alle ore 23:23 divyadaiict <
***@***.***> ha scritto:

**Comment by divyadaiict** [comment]
Thanks edited.
