### ISSUE TITLE
Training on other dataset

### ISSUE THREAD

**Issue by rik030** [mdciri/Vox2Vox#9]
Can I run this architecture on MyoPS 2020 dataset which have 6 class segmentation?

**Comment by mdciri** [comment]
Dear Rishav,

Yes you can. On the Readme.md file there is written how:

python ./main.py

'-nc' or '--num_classes': number of classes, default 4


Best regards,
Marco

**Comment by rik030** [comment]
Hello Sir,
In the Brats20 dataset, the modalities are 240x240x155 for every patient but in MyoPS dataset, shapes are different for different patients like patient 1 has 192x168x5 for each modality while patient 2 has 255x179x3 for each modality. Here we have only 3 modalities (bssfp, T2, and LGE). How to tackle this situation?

**Comment by mdciri** [comment]
You should fix your dataset first in order to have images/volumes with same
shape (zero padding may help).

Then if your dataset images/volumes have 3 channels you should check, and
in case edit, the input layer of the generator and discriminator.


Best regards,
Marco Domenico Cirillo

**Comment by rik030** [comment]
Hello Sir,
From zero padding, I can change the first two dimensions to get the same shape, but for the number of slices(which varies from 3 to 5), how can I make it the same?

**Comment by mdciri** [comment]
I don't know your dataset. But what you can do is or adding 0s slices to
those volumes with 3, or remove 2 to those with 5. All volumes must have
same shape.

Another thing you can do is training a cycle gan to go from volumes with 3
slices to volumes with 5.

Anyway, these solving problems do no concern the vox2vox model.


Best regards,
Marco Domenico Cirillo

**Comment by rik030** [comment]
Hello Sir,
Wouldn't adding 0s slices to those volumes with 3 or 4, affect the model training, as we are assigning class 0 to the background in the ground truth as well.
